# local
spring:
    config:
        import: 'aws-parameterstore:'
        activate:
            on-profile: local
    datasource:
        url: jdbc:mysql://localhost:3306/fitme?useSSL=false&serverTimezone=Asia/Seoul
        username: ssafy
        password: ssafyssafy
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
            logging:
                level:
                    org:
                        hibernate.SQL: debug
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.MySQLDialect

    batch:
        job:
            name: ${job.name:NONE}
        jdbc:
            initialize-schema: always
            schema: classpath:org/springframework/batch/core/schema-mysql.sql

logging:
    level:
        root: info